/**
 * Catalogue des codes d'erreur metier EcomFlow.
 *
 * Contrat d'API : toute reponse d'erreur suit la forme
 * ```json
 * {
 *   "statusCode": 409,
 *   "code": "ORDER_INVALID_TRANSITION",
 *   "message": "Transition CONFIRMED -> SHIPPED interdite.",
 *   "details": { "from": "CONFIRMED", "to": "SHIPPED" },
 *   "correlationId": "01J...",
 *   "timestamp": "2026-08-29T10:00:00.000Z"
 * }
 * ```
 * Le champ `code` est stable et destine au client (front, integrations, tests).
 * Le champ `message` est destine a l'humain et peut evoluer.
 */

export const ERROR_CODES = {
  // --- Generique ---
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',

  // --- Authentification / autorisation ---
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_REUSED: 'AUTH_REFRESH_REUSED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_EMAIL_ALREADY_USED: 'AUTH_EMAIL_ALREADY_USED',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_TOO_MANY_ATTEMPTS: 'AUTH_OTP_TOO_MANY_ATTEMPTS',
  FORBIDDEN: 'FORBIDDEN',
  PERMISSION_DENIED: 'PERMISSION_DENIED',

  // --- Multi-tenant ---
  TENANT_CONTEXT_MISSING: 'TENANT_CONTEXT_MISSING',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_ACCESS_DENIED: 'TENANT_ACCESS_DENIED',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  CROSS_TENANT_ACCESS_BLOCKED: 'CROSS_TENANT_ACCESS_BLOCKED',

  // --- Abonnement ---
  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_SUSPENDED: 'SUBSCRIPTION_SUSPENDED',
  PLAN_LIMIT_REACHED: 'PLAN_LIMIT_REACHED',
  TRIAL_ALREADY_USED: 'TRIAL_ALREADY_USED',
  TRIAL_ABUSE_SUSPECTED: 'TRIAL_ABUSE_SUSPECTED',

  // --- Paiements ---
  PAYMENT_PROVIDER_UNAVAILABLE: 'PAYMENT_PROVIDER_UNAVAILABLE',
  PAYMENT_ALREADY_SETTLED: 'PAYMENT_ALREADY_SETTLED',
  PAYMENT_SIGNATURE_INVALID: 'PAYMENT_SIGNATURE_INVALID',
  PAYMENT_PROOF_REQUIRED: 'PAYMENT_PROOF_REQUIRED',

  // --- Commandes ---
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_INVALID_TRANSITION: 'ORDER_INVALID_TRANSITION',
  ORDER_TRANSITION_GUARD_FAILED: 'ORDER_TRANSITION_GUARD_FAILED',
  ORDER_REASON_REQUIRED: 'ORDER_REASON_REQUIRED',
  ORDER_ALREADY_EXISTS: 'ORDER_ALREADY_EXISTS',
  ORDER_EMPTY_ITEMS: 'ORDER_EMPTY_ITEMS',
  ORDER_ARCHIVED: 'ORDER_ARCHIVED',
  ORDER_DUPLICATE_SUSPECTED: 'ORDER_DUPLICATE_SUSPECTED',

  // --- Stock ---
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  INVENTORY_NEGATIVE_RESULT: 'INVENTORY_NEGATIVE_RESULT',
  VARIANT_NOT_FOUND: 'VARIANT_NOT_FOUND',
  SKU_ALREADY_EXISTS: 'SKU_ALREADY_EXISTS',

  // --- Expedition ---
  SHIPMENT_ALREADY_EXISTS: 'SHIPMENT_ALREADY_EXISTS',
  SHIPMENT_NOT_FOUND: 'SHIPMENT_NOT_FOUND',
  CARRIER_NOT_CONFIGURED: 'CARRIER_NOT_CONFIGURED',
  CARRIER_API_ERROR: 'CARRIER_API_ERROR',
  CARRIER_TIMEOUT: 'CARRIER_TIMEOUT',
  CARRIER_CIRCUIT_OPEN: 'CARRIER_CIRCUIT_OPEN',
  CARRIER_REJECTED_ORDER: 'CARRIER_REJECTED_ORDER',
  TRACKING_NOT_AVAILABLE: 'TRACKING_NOT_AVAILABLE',

  // --- Integrations / Google Sheets ---
  INTEGRATION_NOT_FOUND: 'INTEGRATION_NOT_FOUND',
  INTEGRATION_NOT_CONNECTED: 'INTEGRATION_NOT_CONNECTED',
  GOOGLE_AUTH_EXPIRED: 'GOOGLE_AUTH_EXPIRED',
  GOOGLE_AUTH_REVOKED: 'GOOGLE_AUTH_REVOKED',
  GOOGLE_SHEET_NOT_FOUND: 'GOOGLE_SHEET_NOT_FOUND',
  GOOGLE_SHEET_TAB_NOT_FOUND: 'GOOGLE_SHEET_TAB_NOT_FOUND',
  GOOGLE_SHEET_COLUMN_MISSING: 'GOOGLE_SHEET_COLUMN_MISSING',
  GOOGLE_QUOTA_EXCEEDED: 'GOOGLE_QUOTA_EXCEEDED',
  GOOGLE_API_UNAVAILABLE: 'GOOGLE_API_UNAVAILABLE',
  MAPPING_INVALID: 'MAPPING_INVALID',
  SYNC_ALREADY_RUNNING: 'SYNC_ALREADY_RUNNING',

  // --- WhatsApp ---
  WHATSAPP_NOT_CONFIGURED: 'WHATSAPP_NOT_CONFIGURED',
  WHATSAPP_SEND_FAILED: 'WHATSAPP_SEND_FAILED',
  WHATSAPP_TEMPLATE_REJECTED: 'WHATSAPP_TEMPLATE_REJECTED',

  // --- Retours ---
  RETURN_ALREADY_EXISTS: 'RETURN_ALREADY_EXISTS',
  RETURN_NOT_FOUND: 'RETURN_NOT_FOUND',
  RETURN_INVALID_STATE: 'RETURN_INVALID_STATE',

  // --- Roles & utilisateurs ---
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_IMMUTABLE: 'ROLE_IMMUTABLE',
  ROLE_IN_USE: 'ROLE_IN_USE',
  LAST_OWNER_PROTECTED: 'LAST_OWNER_PROTECTED',
  USER_ALREADY_MEMBER: 'USER_ALREADY_MEMBER',

  // --- Export / import ---
  EXPORT_TOO_LARGE: 'EXPORT_TOO_LARGE',
  IMPORT_FILE_INVALID: 'IMPORT_FILE_INVALID',
  IMPORT_ALREADY_PROCESSED: 'IMPORT_ALREADY_PROCESSED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/** Charge utile normalisee renvoyee par l'API pour toute erreur. */
export interface ApiErrorBody {
  readonly statusCode: number;
  /**
   * Code d'erreur metier.
   *
   * `string & {}` plutot que `string` : l'union conserve l'autocompletion sur
   * les codes connus tout en acceptant un code inconnu. Ecrire
   * `ErrorCode | string` ferait s'effondrer l'union en `string` et priverait
   * les clients de toute aide au typage.
   */
  readonly code: ErrorCode | (string & {});
  readonly message: string;
  readonly details?: Record<string, unknown>;
  readonly correlationId?: string;
  readonly timestamp: string;
  readonly path?: string;
}

/**
 * Erreurs pour lesquelles une nouvelle tentative a du sens cote appelant
 * (utilise par le client HTTP du front et par la politique de retry des jobs).
 */
export const RETRYABLE_ERROR_CODES: readonly ErrorCode[] = [
  ERROR_CODES.RATE_LIMITED,
  ERROR_CODES.INTERNAL_ERROR,
  ERROR_CODES.CARRIER_TIMEOUT,
  ERROR_CODES.CARRIER_API_ERROR,
  ERROR_CODES.GOOGLE_QUOTA_EXCEEDED,
  ERROR_CODES.GOOGLE_API_UNAVAILABLE,
  ERROR_CODES.PAYMENT_PROVIDER_UNAVAILABLE,
  ERROR_CODES.WHATSAPP_SEND_FAILED,
];

export function isRetryableErrorCode(code: string): boolean {
  return (RETRYABLE_ERROR_CODES as readonly string[]).includes(code);
}
